version: '3'
services:
  php:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .\code:/var/www/html
  
  phpadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
  
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
    volumes:
      - .\data:/var/lib/mysql
      - .\config:/etc/mysql/conf.d
    ports:
      - "3306:3306"